#pragma once

#define UAPI_PCI_CFG_VENDOR_ID 0x0
#define UAPI_PCI_CFG_DEVICE_ID 0x2
#define UAPI_PCI_CFG_COMMAND 0x4
#define UAPI_PCI_CFG_STATUS 0x6
#define UAPI_PCI_CFG_REVISION_ID 0x8
#define UAPI_PCI_CFG_PROG_IF 0x9
#define UAPI_PCI_CFG_SUBCLASS 0xA
#define UAPI_PCI_CFG_CLASS_CODE 0xB
#define UAPI_PCI_CFG_CACHE_LINE_SIZE 0xC
#define UAPI_PCI_CFG_LATENCY_TIMER 0xD
#define UAPI_PCI_CFG_HEADER_TYPE 0xE
#define UAPI_PCI_CFG_BIST 0xF
#define UAPI_PCI_CFG_BAR(index) (0x10 + ((index) * 0x4))
#define UAPI_PCI_CFG_CARDBUS_CIS 0x28
#define UAPI_PCI_CFG_SUBSYSTEM_VENDOR_ID 0x2C
#define UAPI_PCI_CFG_SUBSYSTEM_ID 0x2E
#define UAPI_PCI_CFG_EXPANSION_ROM 0x30
#define UAPI_PCI_CFG_CAPABILITIES 0x34
#define UAPI_PCI_CFG_INTERRUPT_LINE 0x3C
#define UAPI_PCI_CFG_INTERRUPT_PIN 0x3D
#define UAPI_PCI_CFG_MIN_GRANT 0x3E
#define UAPI_PCI_CFG_MAX_LATENCY 0x3F
